# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fc9faadab842dc9ede4b78a10139e97ed54fa332cdefdbb90742e1fbcb43e1afd5274a655bcb064b18995f4084fb5f2a8a759fbcb3f4e806634953f6ec16288a

test:
  secret_key_base: e413afd1358b743a6cbbc9f2b0d153c66de39c4c5f79c6c24bf5af6920eeac9a46269dee91ede67bbf61e1c975b6d0d78ee6e7566b365571bc051eb0d9cfe536

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
